### ISSUE TITLE
Screenshots should only show your application

### ISSUE THREAD

**Issue by danrabbit** [EFDos/mupengui#5]
Hey thanks for your AppCenter submission! I'm marking this release as "Needs Fixing" since screenshots should only show your application, not your full desktop. You can get a screenshot of just your application with the built in Screenshot app and the second capture option ("Grab the current window")

https://github.com/EFDos/mupengui/blob/6e3185f66411ad5f926062cecc82de54d762e563/data/com.github.efdos.mupengui.appdata.xml.in#L66

**Comment by EFDos** [comment]
Thanks Dan! This is fixed now, I'll update the release to the latest commit.
