### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [EFDos/mupengui#6]
Arch Linux Support

I will support your application in Arch Linux. Please, consider to use 2 branchs: master (stable code), develop (development code).

Please add a section containing the following instruction:

## Arch Linux
Arch Linux users can find `MupenGui` under the name [mupengui-git](https://aur.archlinux.org/packages/mupengui-git/) in the **AUR**:

`$ aurman -S mupengui-git`

**Comment by EFDos** [comment]
That's great! Really nice to know!

By tomorrow I should get some time to work on mupengui, I'll be sure to 
create a second branch for development and
add the Arch Linux instructions on the Readme.

Thank you!
